Resources:
  postsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-postsTable-${sls:stage}
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: unixtime
          AttributeType: N
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: unixtime
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  s3BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${sls:instanceId}-dynamobackup-${sls:stage}
