version: '3.8'
services:

  dynamodb.local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    # volumes:
    #   - ./db:/home/dynamodblocal/db
    # command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/db"]
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    working_dir: /home/dynamodblocal
    expose:
      - "8000"

  dynamodb.admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb.local:8000"
      AWS_REGION: "eu-west-3"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb.local
