console: true
org: danielesalvagni
app: social-networking-serverless-kata
service: social-networking-serverless-kata
frameworkVersion: '3'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider: ${file(yml/provider.yml)}

custom: ${file(yml/custom.yml)}

functions: ${file(yml/functions.yml)}

resources:
  Resources: ${file(yml/resources.yml)}

package:
  individually: true
  patterns:
    - '!./**'  # exclude everything
    - 'src/**' # include everything inside src
