postTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy : Retain
  Properties:
    TableName: ${self:service}-postTable-${sls:stage}
    AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      - AttributeName: unixtime
        AttributeType: N
    KeySchema:
      - AttributeName: username
        KeyType: HASH
      - AttributeName: unixtime
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
